server:
  port: 8001
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:./h2/weather;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      # this enables http://localhost:8080/api/h2-console
      # username/password are sa (defined few lines above)
      enabled: true

app:
  jwt:
    secret: c2VjcmV0
    duration-min: 30

  users:
    userName: user
    userPassword: user
    adminName: admin
    adminPassword: admin

